<?php

//-------------------------------------------
//-------------- P-Space HOOKS --------------
//-------------------------------------------

function pspace_lights_menu()
{
$stoixeia=array();

$stoixeia['lights']=array(
	'title'=> t('P-Space Lights Page'),
	'page callback' => 'lights_overview',
	'access callback'=>TRUE,
);

return $stoixeia;
}


function pspace_lights_permission() {
  
  $perm_array= array(
    'open/close_lights' => array(
      'title' => t('Open/Close lights'), 
	  //'restrict access' => TRUE
    ),
  );
	
  return $perm_array;
}

/*
function pspace_lights_init() {
  
 drupal_add_js(drupal_get_path('module', 'pspace_lights') . '/websocket.js');

}*/


//-------------------------------------------
//-------------- P-Space PAGES --------------
//-------------------------------------------


function lights_overview()
{
$rarray=array();



$testbed = variable_get_value('pspace_rest');

$node_pref = variable_get_value('pspace_node_prefix');
$cap_pref = variable_get_value('pspace_capability_prefix');


//hardcoded: node / capability / room
$node= $node_pref."0x2eb";
$capability= $cap_pref . "lamp1";
$vcapability= $cap_pref . "light1";

$room = "room_3";   
//test
//$virtual=$node_pref.'virtual:0.I.9';
//general
//$virtual=$node_pref.'virtual:'.$room;
//pspace
$virtual=$node_pref.'virtual:ROOM1';


 $rarray['svg']= array(
  '#markup' => file_get_contents ("sites/all/themes/1200.svg"), 
  '#prefix' => "<div class=\"svg\" >",
  '#suffix' => "</div>",
  );

 
$json=file_get_contents("$testbed/node/".$node."/capability/".$capability."/latestreading/json");
$light=get_object_vars(json_decode($json));
 
$haslight= $light['readings'][0]->reading;
 
$script="";
$header="<script type=\"text/javascript\">";
if ($haslight)
	$script.="document.getElementById(\"$room\").style.opacity=0;";  //lights on
	//$script="document.getElementById(\"$room\").style.opacity=0.688;"; //lights off
$footer="</script>\n";

 $rarray['script_image']= array(
  '#markup' => $header.$script.$footer, 
  );
  
//-------------- switches -------------//
  
if (user_access("open/close_lights")){


 $script="var state=new Array();" ;
    
  
if ($haslight)	$script.="state[3]=1;";
else $script.="state[3]=0;";

$script.="	function activate(node,room){";

//$script.="alert('$testbed/node/$virtual/capability/$capability/insert/timestamp/'+timestamp+'/reading/0/');";

//room 3: send command and w8 for socket to change state in webpage


$script.="if (room==3){ var timestamp = new Date().valueOf(); xmlhttp=new XMLHttpRequest();";
$script.="if (state[3]==0) xmlhttp.open(\"GET\",'$testbed/node/$virtual/capability/$vcapability/insert/timestamp/'+timestamp+'/reading/1/');";
$script.="else xmlhttp.open(\"GET\",'$testbed/node/$virtual/capability/$vcapability/insert/timestamp/'+timestamp+'/reading/0/');";
$script.="xmlhttp.send();xmlhttp.send();";
$script.="}";


//for other rooms play dummy graphics
$script.="else{";
$script.="if (state[room]==1){state[room]=0; document.getElementById('myswitch'+room).src=\"sites/all/themes/newswitch0.png\";document.getElementById('room_'+room).style.opacity=0.688;}";
$script.="else{	state[room]=1; document.getElementById('myswitch'+room).src=\"sites/all/themes/newswitch1.png\"; document.getElementById('room_'+room).style.opacity=0;	}";
$script.="}";


$script.="}";


	  
$rarray['script_light']= array(
  '#markup' => $header.$script.$footer, 
  );


$script2="function onwsmessage(livestring){";


$script2.="var command=livestring.split(\" \");";
$script2.="if (command[8]==\"0.0\"){state[3]=0; document.getElementById('myswitch3').src=\"sites/all/themes/newswitch0.png\";document.getElementById('room_3').style.opacity=0.688;}";
$script2.="else{state[3]=1; document.getElementById('myswitch3').src=\"sites/all/themes/newswitch1.png\"; document.getElementById('room_3').style.opacity=0;	}";

$script2.="}";

$rarray['script_websock_light']= array(
  '#markup' => $header.$script2.$footer, 
  );


  
$item= "<img src=\"sites/all/themes/newswitch0.png\" onclick = \"activate(0,1)\" title=\"room 1\" id= \"myswitch1\" alt=\"switch\" height=\"100\" width=\"100\"/>"; 
$item.= "<img src=\"sites/all/themes/newswitch0.png\" onclick = \"activate(0,2)\" title=\"room 2\"id= \"myswitch2\" alt=\"switch\" height=\"100\" width=\"100\"/>"; 
  
if ($haslight) $item .=  "<img src=\"sites/all/themes/newswitch1.png\" onclick = \"activate('$node',3)\" title=\"room 3\" id= \"myswitch3\" alt=\"switch\" height=\"100\" width=\"100\"/>"; 
else $item .=  "<img src=\"sites/all/themes/newswitch0.png\" onclick = \"activate('$node',3)\" title=\"room 3\" id= \"myswitch3\" alt=\"switch\" height=\"100\" width=\"100\"/>"; 

$item.= "<img src=\"sites/all/themes/newswitch0.png\" onclick = \"activate(0,4)\" title=\"room 4\" id= \"myswitch4\" alt=\"switch\" height=\"100\" width=\"100\"/>"; 

  $rarray['switch_images'] = array(
   		    '#markup' =>  $item,
	  );
  }
else{

$script2="var state=new Array();" ;


if ($haslight)  $script2.="state[3]=1;";
else $script2.="state[3]=0;";

$script2.="function onwsmessage(livestring){";
$script2.="var command=livestring.split(\" \");";
$script2.="if (command[8]==\"0.0\"){state[3]=0; document.getElementById('room_3').style.opacity=0.688;}";
$script2.="else{state[3]=1; document.getElementById('room_3').style.opacity=0;    }";

$script2.="}";

$rarray['script_websock_light']= array(
  '#markup' => $header.$script2.$footer,
  );
}


$ws="<script type=\"text/javascript\" src=\"http://pspace.dyndns.org/drupal/sites/all/modules/pspace/pspace_lights/websocket.js\"></script>\n";


$script3=" connect(\"pspace.dyndns.org:8080/uberdust\",\"urn:pspace:0x2eb\",\"urn:node:capability:lamp1\");\n";

$rarray['script_connect']= array(
  '#markup' => $ws.$header.$script3.$footer, 
  );


return $rarray;
}
